line_length:
  warning: 500
  error: 1000

disabled_rules:
- trailing_whitespace
- force_cast
- identifier_name
- weak_delegate
- for_where
- redundant_optional_initialization
- colon
- unused_closure_parameter
- class_delegate_protocol
